version: '3.9'
services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
      - "80:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./public:/app/public
      - ./.env:/app/.env
      - ./scripts:/app/scripts
    networks:
      - base
  
  db:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "2255:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
      - ./config/netcraft_db.sql:/docker-entrypoint-initdb.d/netcraft_db.sql
    networks:
      - base

networks:
  base:
    driver: bridge

